version: '1.0'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: playWords_db 
      MYSQL_USER: ulises
      MYSQL_PASSWORD: 1234 
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - mynetwork

  backend:
    build: .
    container_name: backend_container
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: ulises 
      DATABASE_PASSWORD: 1234 
      DATABASE_NAME: playWords_db 
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge